### ISSUE TITLE
Api keys

### ISSUE THREAD

**Issue by Johnnywick1** [benchan79/weather-app#2]
Could you tell us how to install API Keys?
I put Api keys on .env file GOOGLE_MAPS_API_KEY= 
OWM_API_KEY=
but it's not working

**Comment by benchan79** [comment]
I'm using netlify functions to access the keys. You have to install the **netlify CLI** and run `netlify dev` instead of `npm start` 

[How to Securely Access Secret API keys using Netlify Functions in a React App](https://www.freecodecamp.org/news/how-to-access-secret-api-keys-using-netlify-functions-in-a-react-app/)

First install netlify CLI
```
npm install netlify-cli -g
```

Then run
```
netlify dev
```

Actually, the keys are not entirely hidden. That's because of the library `@react-google-maps/api` I used. You can still see them inside the Developer's Tools. I'm just practicing how to use netlify functions for my own knowledge. Also, I'm using OpenWeather's [**Developer's Plan**](https://openweathermap.org/price#current) which allows me to fetch daily and hourly forecasts. You will not be able to fetch them if your OpenWeather API key is generated by the [**Free**](https://openweathermap.org/price#current) plan.  You also have to make sure your Google Maps API key is activated for the following: [**Geocoding API**](https://developers.google.com/maps/documentation/geocoding/cloud-setup) and [**Maps JavaScript API**.](https://developers.google.com/maps/documentation/javascript/cloud-setup)

**Comment by Johnnywick1** [comment]
Thank you very much. I managed it, but I have just another question. Is it possible to install this script on other platforms. For example I tried to install this script on codesandbox, vercell.app and there is not working. Only in Netlify works. Your team mate Shaynesoh made similar script and it works on Vercell and Codesandbox but the map in his script doesn't show. Is it possible to install your script in Codesandbox ? (Maybe you can make that Api keys doesn not import from .env file but from the files where they are, if you know what I mean... my english is not good)

Thank you for you answer

**Comment by Johnnywick1** [comment]
I've seen that you made some changes even for  those who not installing Netlify cli. Could you check this link? I've done like you have written but still not working for me. Could you see this link and check what I have done wrong?

https://codesandbox.io/p/github/Johnnywick1/weather-app-map/draft/sharp-zhukovsky?file=%2Fnetlify%2Ffunctions%2FowmZip.js&selection=%5B%7B%22endColumn%22%3A52%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A52%2C%22startLineNumber%22%3A5%7D%5D

I don't have any idea...

Thank you

**Comment by benchan79** [comment]
Hi. If you do a `git checkout b41074840fcac5ce3db489ace4f9d6f2d4e49a75`, you will checkout to an older commit to see what the old code looks like before I started using netlify functions. When you've finished browsing, you can do a `git checkout main` to return to the main branch. 

**You do not need the netlify functions anymore.** 

The files you have to make changes to are:
 
1. src/components/MapDisplay.js
2. src/services/geoAPI.js
3. src/services/weatherApi.js

**Comment by benchan79** [comment]
I have made a branch called `without-netlify` that runs everything without using netlify functions. See the updated README for more info.

**Comment by Johnnywick1** [comment]
THANK YOU SO MUCH. NOW IT"S WORKING. Thank you!!! I will try now to put the map next to day weather info. I don't want you bother  more  cause you helped me a lot but if you find some FREE time to make this it would be awsome.  Thank you again!!!

**Comment by benchan79** [comment]
No worries. Have a good weekend.

**Comment by Johnnywick1** [comment]
You too.
